[package]
name = "linux-usb-writer"
version = "0.1.0"
edition = "2024"

[dependencies]
ctrlc = "3.5.2"
flate2 = { version = "1.1.10", default-features = false, features = ["rust_backend", "runtime_detection"] }
liblzma = { version = "0.4.8", features = ["static"] }
zbus = { version = "5.19.0", features = ["blocking-api"] }
